id: IF0E480B6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T07:43:28+00:00'
last_modified: '2022-06-08T09:33:46.574582+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD152286
  title: བོད་ཀྱི་ལྷ་མོའི་ཟློས་གར་གྱི་འཁྲབ་གཞུང་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    06A1:
      image_group_id: I2PD19027
      title: ''
      total_pages: 674
      order: 1
      base_file: 06A1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
