id: P009233
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD152286
  title: བོད་ཀྱི་ལྷ་མོའི་ཟློས་གར་གྱི་འཁྲབ་གཞུང་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    551ae08919ed490d8c7fe4de8a0341c3:
      image_group_id: I2PD19027
      title: ''
      volume_number: 1
      total_pages: 674
      base_file: v001.txt
